services:
  short-url:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url
    ports:
      - '5600:5600'
    restart: always
    # 如果需要环境变量，可以添加：
    # environment:
    #   - NODE_ENV=production
    #   - DATABASE_URL=your_database_url
    # 如果需要挂载卷：
    # volumes:
    #   - ./data:/app/data
