networks:
  1panel-network:
    external: true

services:
  short-url:
    build:
      context: .
      dockerfile: Dockerfile
    image: short-url:latest # 定义镜像名称和标签
    container_name: short-url # 容器名称
    ports:
      - '5600:5600'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - 1panel-network
    restart: always
    # 如果需要环境变量，可以添加：
    # environment:
    #   - NODE_ENV=production
    #   - DATABASE_URL=your_database_url
    # 如果需要挂载卷：
    # volumes:
    #   - ./data:/app/data
